# Generated by Django 5.0 on 2024-01-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('desc', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('img', models.FileField(blank=True, null=True, upload_to='cine/img')),
            ],
        ),
        migrations.DeleteModel(
            name='Films',
        ),
    ]
