# Generated by Django 5.0 on 2024-02-08 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cine', '0002_cine_delete_films'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cine',
            name='id',
        ),
        migrations.AlterField(
            model_name='cine',
            name='name',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
